### ISSUE TITLE
Configurable icon

### ISSUE THREAD

**Issue by ullebe1** [claustromaniac/detect-cloudflare-plus#10]
I really like the addon, but seing the eye in my address bar, it feels out of place. Having the option of using a flat icon consistent with the visual style of the rest of Firefox would be great.

**Comment by claustromaniac** [comment]
Thanks for the feedback.

I agree with you, but I think I'd rather change the current icons instead.

What do you think about these?

![eye16](https://user-images.githubusercontent.com/20734810/46131899-4eba9380-c22c-11e8-8740-14c2af11bc0a.png) ![eye-orange-16](https://user-images.githubusercontent.com/20734810/46131906-5417de00-c22c-11e8-960c-64ffc87aea45.png)
![eye-red16](https://user-images.githubusercontent.com/20734810/46131914-5712ce80-c22c-11e8-8e47-6588e9ecd3ec.png) ![eye-purple16](https://user-images.githubusercontent.com/20734810/46131920-59752880-c22c-11e8-82da-7c046adc6ed8.png)

**Comment by claustromaniac** [comment]
Another batch... maybe I overdid the flattening in the previous one.


![eyeb-16](https://user-images.githubusercontent.com/20734810/46161810-150e7a80-c276-11e8-973f-5801ed31fd23.png) ![eyeb-orange16](https://user-images.githubusercontent.com/20734810/46161816-16d83e00-c276-11e8-95ed-07304b7e0d7e.png) ![eyeb-red16](https://user-images.githubusercontent.com/20734810/46161814-15a71100-c276-11e8-8278-5d155cf947b7.png) ![eyeb-purple16](https://user-images.githubusercontent.com/20734810/46161809-13dd4d80-c276-11e8-85c6-b6de25b8333f.png)

**Comment by n8v8R** [comment]
![eyes](https://user-images.githubusercontent.com/13611490/46182505-cb488300-c2bb-11e8-9240-af46cc4ee222.png)

**Comment by claustromaniac** [comment]
> - Include FreePik Contents in an online or offline database or file.
> - Offering FreePik designs (or FreePik --Contents modified versions) for download.

That's ambiguous AF.

> - To use any of Freepik's images as the only or main theme of your designs.

So, would I have to include something else?

Even if I decide to forget about those points, there is something more important to consider. This is what those icons look like in a resolution of 16x16 (with my extra-extra flat edition at the bottom for comparison):

![eyes_16](https://user-images.githubusercontent.com/20734810/46191734-21332000-c2e8-11e8-88e3-e65ae182246b.png)
![eyec16](https://user-images.githubusercontent.com/20734810/46162952-4f2d4b80-c279-11e8-8048-39373b3bc188.png) ![eyec-orange16](https://user-images.githubusercontent.com/20734810/46162960-518fa580-c279-11e8-9acf-1865ade41f3d.png) ![eyec-red16](https://user-images.githubusercontent.com/20734810/46162957-505e7880-c279-11e8-94da-e7fcbaad7121.png) ![eyec-purple16](https://user-images.githubusercontent.com/20734810/46162954-4fc5e200-c279-11e8-9780-af0609407828.png) 

I mean, I know my icons are dull (I mean it), but that's because they have a purpose and I'm super limited in what I can do with a measly 16x16 grid. Visibility is pretty important when it comes to this extension, so I have to have priorities.

I'm willing to try and make something less crappy, but personally, I'd settle for anything that doesn't look like absolute garbage because aesthetics is not the top priority. Top priorities are:

1. Easy to understand and to remember.
2. Good visibility (as good as possible).

... and with a 16x16 grid I can't add any complexity without giving up one or the two of those things to some extent.

**Comment by n8v8R** [comment]
Seeing a flat WX icon like this https://github.com/mozfreddyb/webext-firstpartyisolation/blob/master/icons/fishbowl.svg I thought to give a try myself

![eye](https://user-images.githubusercontent.com/13611490/46216174-89a4f000-c32e-11e8-8338-57b16460a814.png)

**Comment by claustromaniac** [comment]
@n8v8R,

Thanks for that. Do you happen to have those in a higher resolution? I need them to be at least 64x64, preferably 128x128 or more.

The most common resolution used is 16x16, but I want to include copies in different resolutions this time to make sure they look good everywhere. The color doesn't matter (I can recolor them if necessary), but if you could send me that shape in a higher resolution, that would be great.

I forgot to do that when I made the current icons (they are only 64x64) and the aliasing makes the borders look bad when they are displayed in the lower resolutions. I want to avoid that this time around, if I can.

**Comment by n8v8R** [comment]
this is 160 x 160 px SVG

[eye.zip](https://github.com/claustromaniac/detect-cloudflare-plus/files/2430400/eye.zip)

**Comment by n8v8R** [comment]
Thought this one present a network source scan but it might not come that well in 16x16

![source scan](https://user-images.githubusercontent.com/13611490/46244280-0c2fbd00-c3cc-11e8-9202-1d12a38b7fe8.png)

**Comment by claustromaniac** [comment]
> Thought this one might represent a network source scan but it might not come out that well in 16x16

It's nice, but yeah, it is too complex for 16x16. It could work if we used a simplified version for the 16x16 resolution, though. Yes, I forgot to mention that icons of different resolutions don't need to be an exact match. For example, [Decentraleyes](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/) uses this closed eye in 128x128:

![decentraleyes x 128](https://git.synz.io/Synzvato/decentraleyes/raw/master/icons/icon128.png?inline=false)

but it uses this simplified icon in 16x16: ![decentraleyes x 16](https://git.synz.io/Synzvato/decentraleyes/raw/master/icons/icon16.png?inline=false)

So, if we used that one in 128x128

![pic](https://user-images.githubusercontent.com/13611490/46244280-0c2fbd00-c3cc-11e8-9202-1d12a38b7fe8.png)

we could use something like... ![ts](https://user-images.githubusercontent.com/20734810/46250910-898f1800-c434-11e8-9446-12d984e46ffe.png) in 16x16.

Just an idea. Feel free to experiment if you're feeling up to it. Otherwise, I'm good with your previous offer :+1:

**Comment by ullebe1** [comment]
@claustromaniac Thanks for the fast response! 
I think both of the icons by @n8v8R look great, and I agree that for the second one, a simplified version would be better at low resolutions.

**Comment by n8v8R** [comment]
thanks for the feedback 

@claustromaniac  that 16x16 looks good

just one last other idea to throw in the ring - since the colour change/indicator is apparently a major feature of the icon how about changing the background and maintaining the shape colour, this way the shape could perhaps suffice/survive coherently different resolutions (and work also on light/dark browser themes), e.g.

![scource watch blue](https://user-images.githubusercontent.com/13611490/46260593-48f0d680-c4e8-11e8-837f-0f9a06687fc3.png)   ![scource watch red](https://user-images.githubusercontent.com/13611490/46260594-48f0d680-c4e8-11e8-8754-3f2648226c89.png)

![scource watch blue 16](https://user-images.githubusercontent.com/13611490/46260645-fa900780-c4e8-11e8-8f8d-8f395f1964f8.png)  ![scource watch red 16](https://user-images.githubusercontent.com/13611490/46260681-65d9d980-c4e9-11e8-84fc-90258f1e3713.png)

Anyway, this is 128 x 128 SVG 
[source watch.zip](https://github.com/claustromaniac/detect-cloudflare-plus/files/2431812/source.watch.zip)

**Comment by claustromaniac** [comment]
That's nice. It stands out while still being flat :)

That just gave me another idea... A slightly modified version of your first one:

![test](https://user-images.githubusercontent.com/20734810/46276103-999b1a80-c54e-11e8-8f41-779e9501d122.png)

It's not as easy to understand at 16x16, though.

![test16](https://user-images.githubusercontent.com/20734810/46276373-5f7e4880-c54f-11e8-819b-21129ff460aa.png)

This decision is getting harder than I expected. I like the three of your icons. Good job :laughing:

**Comment by ullebe1** [comment]
That new one is also quite good, especially in high resolutions, but I agree that it needs improvement in the 16x16 version. 
After thinking about it, I think I like the first one by @n8v8R the best, as it is more simple and less "busy" than the others.
