### ISSUE TITLE
badge text color w/yellow

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [claustromaniac/detect-cloudflare-plus#11]
![mellowyellow](https://user-images.githubusercontent.com/16656956/46442856-9b392e00-c75a-11e8-9161-71a5cfda2d5b.png)

When the badge counter is yellow, the text would probably be better off being not-white, its basically impossible to read that number - i.e. the little square yellow blob of info in the toolbar - NFI why I included the panel in the pic :)

**Comment by claustromaniac** [comment]
Why I did I get the feeling that you would be the one to bring this up first? :laughing: 

This is actually a known issue. Believe it or not, I even bookmarked [this bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1424620) weeks ago for this occasion. xD

Changing the badge text color is not implemented in FF 62, but it is already implemented in FF 63. The nicest thing is the text color defaults to white or black depending on the background's color (it changes automatically), so that issue is already solved in the current nightly & dev builds.

All we have to do is wait. I mean, I could do something like change the badge color to a darker tone for people on FF <63, but it is such a minor issue and I've been so busy with other stuff that I didn't even think much about it.

**Comment by Thorin-Oakenpants** [comment]
> I could do something like change the badge color

I suspected as much re API limitations but seriously couldn't be arsed checking - so I just delegated it to you. No need to do anything, it's only 3 weeks or so until 63 lands

**Comment by Thorin-Oakenpants** [comment]
> It must be that you like it :heart: 

Of course :kiss:

**Comment by Thorin-Oakenpants** [comment]
I knew something was preventing me from sleeping ... and I worked it out a few hours ago (just got home) ... if the API isn't backported to ESR, then maybe you should consider using a different shade of yellow - darker, less saturation. Up to you.

**Comment by StanGets** [comment]
It's actually possible to change an extension's toolbar button badge  colors using userChrome.css.
For instance with the _True Sight_ extension we could have:

```
#detect-cloudflare-pa_cm_org-browser-action .toolbarbutton-badge  {
box-shadow: none !important; border: 1px solid #000 !important; background-color: #FFFF00 !important; color: #000 !important;}
```

Side-note: it is this above setting that I use for all badges with the general code:
```
/* All badges : cosmetic */
.toolbarbutton-badge-stack .toolbarbutton-badge {
box-shadow: none !important; border: 1px solid #000 !important; background-color: #FFFF00 !important; color: #000 !important;}
```
because default Firefox settings bother my eyes.

I should have started by this : True Sight is a most valuable extension and now that it's been developed to consider CDNs as a whole I've definitely adopted it. Works nicely, so useful. Many thanks.

**Comment by claustromaniac** [comment]
@StanGets
Thanks for the cool tip!

**Comment by earthlng** [comment]
FWIW the yellow pageAction icon is also hard to see in the default light FF theme. Orange was much better.
