### ISSUE TITLE
Optional setting to block pages hosted by CDNs

### ISSUE THREAD

**Issue by ajvsol** [claustromaniac/detect-cloudflare-plus#20]
For users with the strictest privacy preferences, this would help a great deal. If the heuristics detect a webpage with CDNs then users could be redirected to a page warning them the website was infected with CDNs, and show a list of what ones were used. 

Potential later enhancements:
- Separate settings for whole pages hosted by CDNs and ones with only assets hosted
- Whitelist/blacklist 
- Sharing button on the warning page to publicly shame these offending websites on social media or by emailing the warning directly to the webmaster

**Comment by claustromaniac** [comment]
This would be very tricky to implement. Currently, I need response headers to know what CDNs are in use, which means I need a response to take place (even if just for the headers). To have a response I need to make a request first, which means a communication **needs** to take place, and then blocking would only prevent the browser from loading content. This wouldn't be as tricky for some CDNs that use easily-recognizable CNAMEs, because then I would only need to resolve the hostname to find out if they are in use, but most CDNs don't work like that.

I'm not saying this would be a totally pointless exercise, but it would fall slightly out of the scope of the extension anyway, since the main goal is to raise awareness. Not to mention that blocking everything that comes from CDNs would mean blocking easily over 70% of the traffic altogether. In my opinion it's kind of late for that. CDNs started taking over the Internet many years ago and, realistically, no amount of blocking or shaming will change that. That's why this extension is only trying to *inform* users, because *that* it can do more or less effectively. Once you have that information you can decide on your own whether to trust a certain site or to avoid it (or to block it or whatever).

Thanks for the feedback, though.
